FROM python:3.11-slim

# Εγκατάσταση uv για ταχύτητα
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

RUN apt-get update && apt-get install -y libgomp1 && rm -rf /var/lib/apt/lists/*

# Εγκατάσταση των πάντων με uv
RUN uv pip install --system --no-cache \
    fastapi uvicorn mlflow lightgbm xgboost pydantic numpy pandas sqlalchemy psycopg2-binary python-dotenv

COPY src/api.py .

EXPOSE 8000

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]